smartdump support (experimental)

diff --git a/backup_manager/backup_manager b/backup_manager/backup_manager
--- a/backup_manager/backup_manager
+++ b/backup_manager/backup_manager
@@ -8,7 +8,7 @@
 
 # begin 
 
-BM_VERSION="4.5.51"
+BM_VERSION="4.6.1"
 CONFIGDIR=/etc/mariadb
 CONFIGNAME=backup_manager.cnf
 CONFIGFILE=$CONFIGDIR/$CONFIGNAME
@@ -578,7 +578,7 @@ purge_incomplete()
 	[ "$tt" = "" ] && return
 	echo "purging incomplete backup"
 	case "$tool" in
-		'mariabackup'|'xtrabackup'|'mysqldump') 
+		'mariabackup'|'xtrabackup'|'mysqldump'|'smartdump') 
 					rm -f $tt/$fn
 					;;
 		'mariaunpacked'|'mydumper') 
@@ -1157,6 +1157,9 @@ update_backup_status()
 		'mysqldump')
 			echo "update backup_history set backup_size = $(stat -c %s $tt/$fn) where uuid = '$backup_id';" | dbquery $DB
 			;;
+		'smartdump')
+			echo "update backup_history set backup_size = $(stat -c %s $tt/$fn) where uuid = '$backup_id';" | dbquery $DB
+			;;
 		'mydumper')
 			echo "update backup_history set backup_size = $(du -b $tt | cut -f 1) where uuid = '$backup_id';" | dbquery $DB
 			;;
@@ -1199,6 +1202,8 @@ perform_backup()
 			perform_xtra_backup;;
 		'mysqldump')
 			perform_mysqldump_backup;;
+		'smartdump')
+			perform_smartdump_backup;;
 		'mydumper')
 			perform_mydumper_backup;;
 		'binlogs')
@@ -1300,6 +1305,10 @@ check_status()
                         grep -q "^-- Dump completed" $dumptail || status=1
 			echo "update backup_history set status = $status where uuid = '$backup_id';" | dbquery $DB
 			;;
+		'smartdump')
+			[ -s $logfile ] && status=1
+			echo "update backup_history set status = $status where uuid = '$backup_id';" | dbquery $DB
+			;;
 		*)	echo "update backup_history set status = $status where uuid = '$backup_id';" | dbquery $DB
 			;;
 	esac
@@ -1355,7 +1364,7 @@ sqlite_inventory()
 
 usage() 
 {               
-	echo "usage: $0 backup [ mariabackup | mariaunpacked | xtrabackup | zsnapshot | mydumper | mysqldump | binlogs ]" 
+	echo "usage: $0 backup [ mariabackup | mariaunpacked | xtrabackup | zsnapshot | mydumper | mysqldump | smartdump | binlogs ]" 
 	exit 1                  
 }   
 
@@ -1381,6 +1390,8 @@ get_backup_level()
 		'mysqldump') 	level=2
 				dumplist="$3"
 				[ "$dumplist" = "" -o "$dumplist" = "full" ] && dumplist="ALL"
+				;;
+		'smartdump') 	level=2
 				;;
 		'binlogs') level=3;;
 		'mydumper') level=0;;
@@ -1524,6 +1535,8 @@ do_restore()
 			perform_xtra_restore;;
 		'mysqldump')
 			perform_mysqldump_restore;;
+		'smartdump')
+			perform_smartdump_restore;;
 		'mydumper')
 			perform_mydumper_restore;;
 	esac
@@ -1887,6 +1900,26 @@ perform_mydumper_backup()
 	fire_webhook
 }
 
+perform_smartdump_backup()
+{
+	smartdump=$(which smartdump 2>/dev/null)
+	if [ "$smartdump" = "" ]
+	then
+		echo "ERROR: Please install $tool first."
+		clean_exit 1
+	else
+		echo "Performing backup using $tool."
+	fi
+	[ "$password" != "" ] && pass_str="--password $password"
+	[ "$socket" != "" ] && sock_str="--socket $socket"
+	[ "$port" != "" ] && port_str="--port $port"
+	nproc=$(cat /proc/cpuinfo | fgrep -c processor)
+	$smartdump  --dump --lock-timeout=30 --threads $((nproc/2)) --host $host --user $user $pass_str $sock_str $port_str | $compressor | $encryptor 2>/dev/null > $tt/$fn &
+	run_with_timeout
+	update_backup_status
+	fire_webhook
+}
+
 perform_mysqldump_backup()
 {
 	mysqldump=$(which mysqldump 2>/dev/null)
@@ -1913,6 +1946,19 @@ perform_mydumper_restore()
 	path=$(echo "select bulocation from backup_history where uuid = '$uuid';" | dbquery $DB)
 	echo "To restore this $tool dump, please use: myloader -d $path ..."
 	exit 0
+}
+
+perform_smartdump_restore()
+{
+	path=$(echo "select bulocation from backup_history where uuid = '$uuid';" | dbquery $DB)
+	key=$(echo "select cryptkey from backup_history where uuid = '$uuid';" | dbquery $DB)
+	[ "$key" != "" ] && export enc_key="$key"
+	[ "$password" != "" ] && pass_str="--password $password"
+	[ "$socket" != "" ] && sock_str="--socket $socket"
+	[ "$port" != "" ] && port_str="--port $port"
+	nproc=$(cat /proc/cpuinfo | fgrep -c processor)
+	cat $path | $unencryptor 2>/dev/null | $uncompressor | smartdump --stream --threads $((nproc/2)) --host $host --user $user $pass_str $sock_str $port_str
+	status=$?
 }
 
 perform_mysqldump_restore()
